### PR TITLE
feat: ✨  use template repository

### LINKED ISSUE #4: idea: template repo + new repos based on template repo
if we create a template repo, new repos can be prepared with some good defaults and boilerplate

### PR DESCRIPTION
**Pull request by ghostsquad**
resolves #4

### CODE REVIEW

**Comment by smorimoto** [comment]
Hmm... this is not the ideal way.

**Comment by ghostsquad** [comment]
@smorimoto why is this not ideal?

**Comment by smorimoto** [comment]
1) In the first place, this doesn't work
2) It's wrong to set all repositories as having used templates
3) We need Terraform 0.14.x or higher

**Comment by smorimoto** [comment]
And I'm not a big fan of the template itself. That said, it's worth trying, but it's not that simple, so I can't work on it yet. (Because I don't have enough spare time.)

**Comment by ghostsquad** [comment]
I don't have permissions to try a terraform plan, and CI isn't setup for
this project so, I'm at an impasse

Cheers,
Wes

**Comment by smorimoto** [comment]
I'm not going to do this at this **very** moment. So I will close this.

**Pull request closed without merging**
