### PR TITLE
Import asdf-cmake repository

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by smorimoto** [comment]
@amrox Once you have moved the repository, please comment here. I will merge this and import the repository into Terraform appropriately.

**Comment by amrox** [comment]
@smorimoto repository has been moved https://github.com/asdf-community/asdf-cmake

thank you!

**Comment by smorimoto** [comment]
Thank you! I will work on this as soon as I wake up! (It's Japan time, so wait for about 8 hours!)

**Comment by smorimoto** [comment]
@amrox All set!

**Pull request merged**
