### PR TITLE
Added asdf-bitwarden-secrets-manager to infrastructure

### PR DESCRIPTION
**Pull request by FIAV1**

### CODE REVIEW

**Comment by smorimoto** [comment]
I thought about this again, but isn't the name of this repository a little too generic? I think something like the bitwarden secrets manager would be better.

**Comment by FIAV1** [comment]
That's right, I was thinking about it too, i'm gonna fix the naming all around and update pull requests

**Comment by FIAV1** [comment]
btw, do I also have to submit a PR to `asdf-plugins` repo to add the shortname or is it sufficient to follow the guidelines for this community repo?

**Comment by smorimoto** [comment]
Anyway, thanks @FIAV1!

**Pull request merged**
